name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  linux-build:

    runs-on: ubuntu-18.04
    env:
      VulkanSDKVersion: 1.2.131

    steps:
    - uses: actions/checkout@v2
    - name: Download Vulkan SDK
      run: |
        ( wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - )
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{env.VulkanSDKVersion}}-bionic.list http://packages.lunarg.com/vulkan/${{env.VulkanSDKVersion}}/lunarg-vulkan-${{env.VulkanSDKVersion}}-bionic.list
        sudo apt update
        sudo apt install --download-only vulkan-sdk
    - name: Install Vulkan SDK
      run: sudo apt install vulkan-sdk
    - name: CMake
      run: cmake .
    - name: make
      run: make -j 2

  windows-build:

    runs-on: windows-latest
    env:
      CacheDir: cache-dir
#      VulkanSdk: C:\VulkanSDK\${{env.VulkanSDKVersion}}
      VulkanSDKVersion: 1.2.131.2

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{env.CacheDir}}
        key: VulkanSdk2
    - name: Download Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        if (!(Test-Path -Path ${{env.CacheDir}} )){
          New-Item -ItemType directory -Path ${{env.CacheDir}}
          Write-Output "New folder created"
        }
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/windows/VulkanSDK-${{env.VulkanSDKVersion}}-Installer.exe?u= -OutFile ${{env.CacheDir}}/vulkan-sdk-${{env.VulkanSDKVersion}}.exe
    - name: Install Vulkan SDK
      shell: powershell
      run: |
        $installer = Start-Process -FilePath ${{env.CacheDir}}/vulkan-sdk-${{env.VulkanSDKVersion}}.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
    - name: Check Vulkan SDK installation
      shell: powershell
      run: |
        ls -R -d 1 C:\VulkanSDK\${{env.VulkanSDKVersion}}
#        ( gci env:* | sort-object name )
    - name: CMake
      run: cmake . -G "Visual Studio 16 2019" -A x64
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: MSBuild
      run: MSBuild.exe ALL_BUILD.vcxproj -p:Configuration=Release
