name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  linux-build:

    runs-on: ubuntu-18.04
    env:
      VulkanSDKVersion: 1.2.131

    steps:
    - uses: actions/checkout@v2
    - name: Download Vulkan SDK
      run: |
        ( wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - )
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{env.VulkanSDKVersion}}-bionic.list http://packages.lunarg.com/vulkan/${{env.VulkanSDKVersion}}/lunarg-vulkan-${{env.VulkanSDKVersion}}-bionic.list
        sudo apt update
        sudo apt install --download-only vulkan-sdk
    - name: Install Vulkan SDK
      run: sudo apt install vulkan-sdk
    - name: CMake
      run: cmake .
    - name: make
      run: make -j 2

  windows-build:

    runs-on: windows-latest
    env:
      CacheDir: cache-dir
      VulkanSDKVersion: 1.2.131.2

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{env.CacheDir}}
        key: VulkanSdk2
    - name: Download Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        if (!(Test-Path -Path ${{env.CacheDir}} )){
          New-Item -ItemType directory -Path ${{env.CacheDir}}
          Write-Output "New folder created"
        }
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/windows/VulkanSDK-${{env.VulkanSDKVersion}}-Installer.exe?u= -OutFile ${{env.CacheDir}}/vulkan-sdk-${{env.VulkanSDKVersion}}.exe
    - name: Install Vulkan SDK
      shell: powershell
      run: |
        $installer = Start-Process -FilePath ${{env.CacheDir}}/vulkan-sdk-${{env.VulkanSDKVersion}}.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
    - name: Check Vulkan SDK installation
      shell: powershell
      run: |
        ls -R -d 1 C:\VulkanSDK\${{env.VulkanSDKVersion}}
        ( gci env:* | sort-object name )
    - name: CMake
      run: cmake . -G "Visual Studio 16 2019" -A x64
      env:
        VULKAN_SDK: C:\VulkanSDK\${{env.VulkanSDKVersion}}
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: MSBuild
      run: MSBuild.exe ALL_BUILD.vcxproj -p:Configuration=Release

  macos-build:
    runs-on: macos-latest
    env:
      key:  
    
    steps:
    - uses: actions/checkout@v2
#    - name: Download Vulkan SDK
#      run: wget -O vulkansdk-macos-1.2.131.2.tar.gz https://sdk.lunarg.com/sdk/download/1.2.131.2/mac/vulkansdk-macos-1.2.131.2.tar.gz?u=
#    - name: Extract Vulkan SDK
#      run: tar -zxvf vulkansdk-macos-1.2.131.2.tar.gz
    - name: Set Up Env Vars
      uses: allenevans/set-env@v1.0.0
      with:
        overwrite: true
        VULKAN_SDK: "./vulkansdk-macos-1.2.131.2"
        VK_LAYER_PATH: "${{env.VULKAN_SDK}}/etc/vulkan/explicit_layer.d"
        VK_ICD_FILENAMES: "${{env.VULKAN_SDK}}/etc/vulkan/icd.d/MoltenVK_icd.json"
        PATH: "${{env.VULKAN_SDK}}:${{env.VULKAN_SDK}}/bin:${{env.PATH}}"
        DYLD_LIBRARY_PATH: "${{env.VULKAN_SDK}}/lib:$DYLD_LIBRARY_PATH"
    - name: Debug output
      run: |
        ls 
        echo "Path: $VULKAN_SDK"
        echo "Path: $PATH"
      
