name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  linux-build:

    runs-on: ubuntu-18.04
    env:
      VulkanSDKVersion: 1.2.131
      InstallPath: "../vsg"
#https://sdk.lunarg.com/sdk/download/1.2.131.2/linux/vulkansdk-linux-x86_64-1.2.131.2.tar.gz?u=
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{env.VULKAN_SDK}}
        key: VulkanSdkExtractedMacos
    - name: Download Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: wget --no-cookies -O ../vulkansdk-linux-x86_64-${{env.VulkanSDKVersion}}.tar.gz https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/linux/vulkansdk-linux-x86_64-${{env.VulkanSDKVersion}}.tar.gz?u=
    - name: Extract Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: tar -zxvf ../vulkansdk-linux-x86_64-${{env.VulkanSDKVersion}}.tar.gz -C ./
#    - name: Download Vulkan SDK
#      run: |
#        ( wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - )
#        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${{env.VulkanSDKVersion}}-bionic.list http://packages.lunarg.com/vulkan/${{env.VulkanSDKVersion}}/lunarg-vulkan-${{env.VulkanSDKVersion}}-bionic.list
#        sudo apt update
#        sudo apt install --download-only vulkan-sdk
#    - name: Install Vulkan SDK
#      run: sudo apt install vulkan-sdk
    - name: CMake
      run: cmake -D CMAKE_INSTALL_PREFIX="${{env.InstallPath}}" .
      env:
        VULKAN_SDK: ./vulkansdk-linux-x86_64-${{env.VulkanSDKVersion}}
    - name: make
      run: make -j 2
    - run: make install
    - name: Publish artifact
      uses: actions/upload-artifact@v1
      with:
        name: VsgLinux64
        path: "${{env.InstallPath}}"

  windows-build:

    runs-on: windows-latest
    env:
      CacheDir: cache-dir
      VulkanSDKVersion: 1.2.131.2

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{env.CacheDir}}
        key: VulkanSdk2
    - name: Download Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        if (!(Test-Path -Path ${{env.CacheDir}} )){
          New-Item -ItemType directory -Path ${{env.CacheDir}}
          Write-Output "New folder created"
        }
        Invoke-WebRequest -Uri https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/windows/VulkanSDK-${{env.VulkanSDKVersion}}-Installer.exe?u= -OutFile ${{env.CacheDir}}/vulkan-sdk-${{env.VulkanSDKVersion}}.exe
    - name: Install Vulkan SDK
      shell: powershell
      run: |
        $installer = Start-Process -FilePath ${{env.CacheDir}}/vulkan-sdk-${{env.VulkanSDKVersion}}.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
    - name: Check Vulkan SDK installation
      shell: powershell
      run: |
        ls -R -d 1 C:\VulkanSDK\${{env.VulkanSDKVersion}}
        ( gci env:* | sort-object name )
    - name: CMake
      run: cmake . -G "Visual Studio 16 2019" -A x64
      env:
        VULKAN_SDK: C:\VulkanSDK\${{env.VulkanSDKVersion}}
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: MSBuild
      run: MSBuild.exe ALL_BUILD.vcxproj -p:Configuration=Release

  macos-build:
    runs-on: macos-latest
    env:
      VulkanSDKVersion: 1.2.131.2
    
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-${{env.VulkanSDKVersion}}/macOS
        echo ::set-env name=VULKAN_SDK::$VULKAN_SDK
        echo ::set-env name=VK_LAYER_PATH::$VULKAN_SDK/etc/vulkan/explicit_layer.d
        echo ::set-env name=VK_ICD_FILENAMES::$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{env.VULKAN_SDK}}
        key: VulkanSdkExtractedMacos
    - name: Download Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: wget --no-cookies -O ../vulkansdk-macos-${{env.VulkanSDKVersion}}.tar.gz https://sdk.lunarg.com/sdk/download/${{env.VulkanSDKVersion}}/mac/vulkansdk-macos-${{env.VulkanSDKVersion}}.tar.gz?u=
    - name: Extract Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      run: tar -zxvf ../vulkansdk-macos-${{env.VulkanSDKVersion}}.tar.gz -C ./
    - name: CMake
      run: |
        export DYLD_LIBRARY_PATH="$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH"
        export PATH="$VULKAN_SDK:$VULKAN_SDK/bin:$PATH"
        cmake -D CMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/../vsg-$GITHUB_SHA" .
    - name: Make
      run: make -j 2 || echo "Failed but ok"
