name: CI

on:
  push
  pull_request:
    branches:
      - master

jobs:
  linux-build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Download Vulkan SDK
      run: |
        ( wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - )
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.131-bionic.list http://packages.lunarg.com/vulkan/1.2.131/lunarg-vulkan-1.2.131-bionic.list
        sudo apt update
        sudo apt install --download-only vulkan-sdk
    - name: Install Vulkan SDK
      run: sudo apt install vulkan-sdk
    - name: CMake
      run: cmake .
    - name: make
      run: make -j 2

  windows-build:

    runs-on: windows-latest
    env:
      CACHEDIR: cache-dir
      VULKAN_SDK: C:\VulkanSDK\1.2.131.2

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      id: cache
      uses: actions/cache@v1.1.2
      with:
        path: ${{ env.CACHEDIR }}
        key: VulkanSdk2
    - name: Download Vulkan SDK
      if: steps.cache.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        if (!(Test-Path -Path ${{ env.CACHEDIR }} )){
          New-Item -ItemType directory -Path ${{ env.CACHEDIR }}
          Write-Output "New folder created"
        }
        wget https://sdk.lunarg.com/sdk/download/1.2.131.2/windows/VulkanSDK-1.2.131.2-Installer.exe?u= -OutFile ${{ env.CACHEDIR }}/vulkan-sdk-1.2.131.2.exe
    - name: Install Vulkan SDK
      shell: powershell
      run: |
        $installer = Start-Process -FilePath ${{ env.CACHEDIR }}/vulkan-sdk-1.2.131.2.exe -Wait -PassThru -ArgumentList @("/S");
        $installer.WaitForExit();
#      run: .\vulkan-sdk-1.2.131.2.exe /S
    - name: Check Vulkan SDK installation
      shell: powershell
      run: |
        ls -R -d 1 C:\VulkanSDK\1.2.131.2
        ( gci env:* | sort-object name )
#        Write-Output "::set-env name=VULKAN_SDK::C:\\VulkanSDK\\1.2.131.2"
#        setx /M VULKAN_SDK C:\VulkanSDK\1.2.131.2
    - name: CMake
      run: cmake . -G "Visual Studio 16 2019" -A x64
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
    - name: MSBuild
      run: MSBuild.exe ALL_BUILD.vcxproj -p:Configuration=Release
